version: "3.8"

services:
  postgres_db:
    container_name: "postgres_db"
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local:
    driver: bridge