target-version = "py311"

line-length = 88

select = ["E", "W", "F", "I", "B", "C4"]

ignore = ["E501", "C901", "ERA001"]

[format]
quote-style = "double"

[isort]
known-first-party = ["src"]

[flake8-quotes]
inline-quotes = "double"

[docstring-convention]
convention = "google"
